services:
  postgres:
    image: postgres:15
    container_name: loja_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loja
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - loja-network

  clientes-service:
    build: ./clientes-service
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    networks:
      - loja-network

  vendedores-service:
    build: ./vendedores-service
    ports:
      - "3002:3000"
    depends_on:
      - postgres
    networks:
      - loja-network

  produtos-service:
    build: ./produtos-service
    ports:
      - "3003:3000"
    depends_on:
      - postgres
    networks:
      - loja-network

  vendas-service:
    build: ./vendas-service
    ports:
      - "3004:3000"
    depends_on:
      - postgres
    networks:
      - loja-network

  relatorios-service:
    build: ./relatorios-service
    ports:
      - "3005:3005"
    depends_on:
      - postgres
    networks:
      - loja-network

networks:
  loja-network:
    driver: bridge
